// =========================================================================
// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Produced by tools\gen-sponsor-html.py on 2026-08-29 from the plugin's OWN file:
//   F:\google map plugin\extension\content\widget.js
//
// RE-RUN IT WITH:
//   python tools\gen-sponsor-html.py
// then rebuild. It rewrites this file in place and prints what it extracted.
//
// EXTRACTED, NEVER RETYPED, AND NEVER READ AT RUN TIME. The app compiles this header in;
// nothing in the product opens the plugin path. The generator finds each const BY NAME and
// reads its value to the matching terminator, so it still works when the plugin changes.
//
// TWO THINGS IN HERE COST REAL TIME TO FIND. Neither is a simplification opportunity:
//
//   1. THE PANEL CSS IS WRITTEN FOR A SHADOW DOM. `:host` carries the font stack and every
//      custom property, --kofi included. In a flat document it matches nothing, every
//      var() resolves to nothing, and the result is an unfilled Ko-fi button and serif
//      text - which reads as a styling bug rather than a hosting one. So the page below
//      attaches a REAL shadow root and injects the CSS and markup into it, exactly as the
//      plugin does. Not one selector of theirs is rewritten.
//   2. SVG_CUP and SVG_STAR are multi-line CONCATENATIONS in widget.js, not single
//      literals. Reading only the first quoted fragment truncates each icon to its opening
//      <svg> tag, which renders as nothing. Measured sizes at generation time were
//      cup=828 star=2248 bytes; cup=68 star=79 means that bug is back.
//
// The three destinations are substituted HERE, at generation time - the page carries no
// placeholder. They are checked against src\sponsor.h's constants when this runs, because
// webview_host.cpp refuses to open a target that header does not list.
// =========================================================================
#pragma once

#include <string>

namespace cd {

// The panel's natural size in CSS pixels. The host reserves this much room and scales it
// by the monitor's DPI; WebView2 rasterises CSS px at that same scale.
//
// BOTH numbers are MEASURED against this exact page by tools\measure-panel.py - neither is
// read out of the plugin's stylesheet, and the width USED TO BE. That changed when the
// panel became a single row of four: the plugin's `.shell.is-open { width: 272px }`
// describes their ONE-COLUMN stack, so for this page it is the wrong number. It is still
// read at generation time and printed, as provenance only.
//
// Re-measure with:  python tools\gen-sponsor-html.py --measure
//                   python tools\measure-panel.py
//                   (write the result into SHELL_W / SHELL_H, re-run without --measure,
//                    then measure once more - it must come back identical.)
constexpr int kSponsorCssWidth  = 831;
constexpr int kSponsorCssHeight = 65;

// The page, in 1400-byte pieces: MSVC truncates a single string literal past 16380 bytes
// (C2026), and adjacent literals are merged before that cap is applied - so these are
// separate statements, not one concatenation.
inline void AppendSponsorHtml(std::wstring& out) {
    out.reserve(out.size() + 37423);
    out += L"<!doctype html><meta charset='utf-8'><style>html,body{margin:0;padding:0;overflow:hidden;background:transparent}#h{position:absolute;right:0;bottom:0}</style><body><div id='h'></div><script type='text/plain' id='p'><style>\n:host {\n  all: initial;\n  position: fixed;\n  z-index: 2147483000;\n  font-family: -apple-system, \"Segoe UI\", system-ui, Roboto, sans-serif;\n  contain: layout style;\n}\n\n* { box-sizing: border-box; }\n\n:host {\n  --glass-bg: rgba(28, 26, 38, 0.62);\n  --glass-border: rgba(255, 255, 255, 0.13);\n  --glass-blur: 16px;\n  --glass-radius: 14px;\n  --glass-shadow: 0 8px 22px rgba(0, 0, 0, 0.32);\n  --glass-shadow-hover: 0 18px 44px rgba(0, 0, 0, 0.55);\n  --ink-cream: #f0e6d2;\n  --ink-muted: #a99f8c;\n  --accent: #3ecf8e;\n  --accent-ink: #0e2419;\n  --switch-off: #4a4557;\n  --kofi: #d2413e;\n  --ease: cubic-bezier(0.25, 0.1, 0.25, 1);\n  --dur-fast: 200ms;\n  --dur-base: 300ms;\n  --dur-slow: 420ms;\n}\n\n/* Collapsed still shows the words \"Dark Mode\" and its On/Off state -- an icon\n   alone does not tell you whether the thing is currently on, which is the one\n   fact the control exists to convey. */\n.shell {\n  width: 158px;\n  background: var(--glass-bg);\n  border: 0.5px solid var(--glass-border);\n  border-radius: var(--glass-radius);\n  box-shadow: var(--glass-shadow);\n  backdrop-filter: blur(var(--glass-blur)) saturate(1.3);\n  -webkit-backdrop-filter: blur(var(--glass-blur)) saturat";
    out += L"e(1.3);\n  overflow: hidden;\n  color: var(--ink-cream);\n  transition:\n    width var(--dur-base) var(--ease),\n    box-shadow var(--dur-base) var(--ease),\n    transform var(--dur-base) var(--ease);\n}\n\n.shell:hover { transform: scale(1.025); box-shadow: var(--glass-shadow-hover); }\n.shell.is-open { width: 272px; transform: none; box-shadow: var(--glass-shadow-hover); }\n\n/* ---- the always-visible pill ---- */\n\n.pill {\n  all: unset;\n  display: flex;\n  align-items: center;\n  gap: 10px;\n  width: 100%;\n  height: 46px;\n  padding: 0 13px;\n  cursor: pointer;\n  box-sizing: border-box;\n  transition: transform var(--dur-base) var(--ease);\n}\n.pill:focus-visible { outline: 2px solid var(--accent); outline-offset: -3px; border-radius: var(--glass-radius); }\n/* Inset when open so 1.05 fits inside the shell's overflow:hidden. */\n.shell.is-open .pill {\n  width: calc(100% - 16px);\n  margin: 2px 8px 0;\n  border-radius: 10px;\n}\n.shell.is-open .pill:hover { transform: scale(1.05); }\n.shell.is-open .pill:active { transform: scale(0.96); }\n\n.moon {\n  flex: 0 0 20px;\n  width: 20px;\n  height: 20px;\n  color: var(--ink-muted);\n  transition: color var(--dur-base) var(--ease), transform var(--dur-slow) var(--ease);\n}\n.shell.is-on .moon { color: var(--accent); }\n.shell.is-open .moon { transform: rotate(-18deg); }\n\n/* The label is clipped away with the shell when collapsed, so it needs no\n   separate hiding rul";
    out += L"e -- but it must not wrap or it reflows mid-animation. */\n.pill__text { display: flex; flex-direction: column; min-width: 0; white-space: nowrap; }\n.pill__title { font-size: 12.5px; font-weight: 600; letter-spacing: 0.2px; }\n.pill__state { font-size: 10.5px; color: var(--ink-muted); transition: color var(--dur-base) var(--ease); }\n.shell.is-on .pill__state { color: var(--accent); }\n\n.chev {\n  margin-left: auto;\n  width: 14px;\n  height: 14px;\n  color: var(--ink-muted);\n  transition: transform var(--dur-base) var(--ease);\n}\n.shell.is-open .chev { transform: rotate(180deg); }\n\n/* ---- the expanding body ----\n   grid-template-rows 0fr -> 1fr is the one way to transition to an intrinsic\n   height without measuring it in JS, which would desync the moment the panel's\n   content changes. The inner wrapper needs min-height:0 for it to collapse. */\n\n.body {\n  display: grid;\n  grid-template-rows: 0fr;\n  transition: grid-template-rows var(--dur-base) var(--ease);\n}\n.shell.is-open .body { grid-template-rows: 1fr; }\n.body__inner { overflow: hidden; min-height: 0; }\n.body__pad { padding: 2px 13px 13px; }\n\n.rule { height: 0.5px; background: var(--glass-border); margin: 0 0 10px; }\n\n/* Rows fade and rise in, staggered, so the panel assembles rather than\n   appearing. Delays are only on the way in; closing is immediate so the panel\n   never appears to hesitate when the pointer leaves. */\n.row, .";
    out += L"kofi, .gh, .goat {\n  opacity: 0;\n  transform: translateY(-6px);\n  transition: opacity var(--dur-fast) var(--ease), transform var(--dur-base) var(--ease),\n              box-shadow var(--dur-base) var(--ease), background var(--dur-fast) var(--ease);\n}\n.shell.is-open .row,\n.shell.is-open .kofi,\n.shell.is-open .gh,\n.shell.is-open .goat { opacity: 1; transform: none; }\n/* Keyed by data-row, not :nth-of-type -- the rows share a parent with a rule\n   and two paragraphs, so type counting would silently address the wrong ones. */\n.shell.is-open .row[data-row=\"enabled\"]    { transition-delay: 60ms; }\n.shell.is-open .row[data-row=\"darkMap\"]    { transition-delay: 110ms; }\n.shell.is-open .row[data-row=\"darkChrome\"] { transition-delay: 160ms; }\n.shell.is-open .kofi { transition-delay: 210ms; }\n.shell.is-open .gh   { transition-delay: 250ms; }\n.shell.is-open .goat { transition-delay: 290ms; }\n\n/* ---- switch rows ---- */\n\n.row {\n  display: flex;\n  align-items: center;\n  gap: 10px;\n  padding: 7px 0;\n}\n.row__text { min-width: 0; flex: 1; }\n.row__label { display: block; font-size: 12px; font-weight: 500; }\n.row__hint { display: block; font-size: 10.5px; color: var(--ink-muted); margin-top: 1px; }\n.row.is-sub { padding-left: 8px; }\n.row.is-muted .row__label, .row.is-muted .row__hint { color: var(--switch-off); }\n\n.track {\n  all: unset;\n  flex: 0 0 40px;\n  width: 40px;\n  height: 24px;\n  border-ra";
    out += L"dius: 12px;\n  background: var(--switch-off);\n  position: relative;\n  cursor: pointer;\n  transition: background var(--dur-base) var(--ease), box-shadow var(--dur-base) var(--ease),\n              transform var(--dur-base) var(--ease);\n}\n.track.on { background: var(--accent); box-shadow: 0 0 14px rgba(62, 207, 142, 0.35); }\n.track:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }\n.track:disabled { cursor: not-allowed; opacity: 0.45; }\n.thumb {\n  position: absolute;\n  top: 3px;\n  left: 3px;\n  width: 18px;\n  height: 18px;\n  border-radius: 50%;\n  background: #fff;\n  transition: left var(--dur-base) var(--ease);\n}\n.track.on .thumb { left: 19px; }\n.track:not(:disabled):active .thumb { width: 22px; }\n\n/* ---- Ko-fi ---- */\n\n.kofi {\n  all: unset;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  gap: 9px;\n  width: 100%;\n  box-sizing: border-box;\n  margin-top: 4px;\n  padding: 9px 12px;\n  border-radius: 11px;\n  background: var(--kofi);\n  color: #fff;\n  font-size: 12.5px;\n  font-weight: 600;\n  cursor: pointer;\n  box-shadow: 0 6px 18px rgba(210, 65, 62, 0.28);\n  /* Re-declared here, and this is not redundant: the \"all: unset\" at the top of\n     this rule resets transition to none, and this rule comes AFTER the\n     .row/.kofi/.gh block that sets it. Without this the hover scale applied\n     instantly -- the button jumped to 1.05 with no animation wha";
    out += L"tsoever, which\n     is exactly what it looked like. */\n  transition: opacity var(--dur-fast) var(--ease), transform var(--dur-base) var(--ease),\n              box-shadow var(--dur-base) var(--ease), background var(--dur-fast) var(--ease);\n}\n/* The stagger transition above owns opacity/transform, so hover adds its own\n   properties rather than replacing the shorthand. */\n.kofi:hover { background: #e04b48; }\n.kofi:focus-visible { outline: 2px solid #fff; outline-offset: 2px; }\n\n/* Hover lift, taken from the GOAT desktop app so both products answer the\n   pointer the same way: .glass:hover scales and swaps in --glass-shadow-hover,\n   .primary-cta scales 1.05 on hover and 0.96 on press.\n   Scoped under .shell.is-open because the entry-stagger rule parks transform\n   at none at the same specificity -- unscoped, whichever came last would win\n   and the lift would be a coin flip. */\n.shell.is-open .kofi:hover,\n.shell.is-open .gh:hover,\n.shell.is-open .goat-lockup:hover { transform: scale(1.05); }\n.shell.is-open .kofi:active,\n.shell.is-open .gh:active,\n.shell.is-open .goat-lockup:active { transform: scale(0.96); }\n.shell.is-open .track:not(:disabled):hover { transform: scale(1.15); }\n.shell.is-open .track:not(:disabled):active { transform: scale(0.96); }\n\n/* The entry stagger above parks a 210ms/250ms transition-delay on these two\n   buttons, and a delay set in one rule keeps applying ";
    out += L"in every other state.\n   Hovering therefore sat still for a fifth of a second before the scale began,\n   which reads as \"the button does not animate\" -- and it is invisible to any\n   assertion that only samples the final transform. Clear it for the pointer\n   states so the lift starts on the same frame as the pointer arrives. */\n.shell.is-open .kofi:hover, .shell.is-open .kofi:active,\n.shell.is-open .gh:hover,   .shell.is-open .gh:active,\n.shell.is-open .goat-lockup:hover, .shell.is-open .goat-lockup:active,\n.shell.is-open .track:hover, .shell.is-open .track:active { transition-delay: 0s; }\n\n.kofi:hover { box-shadow: var(--glass-shadow-hover), 0 10px 26px rgba(210, 65, 62, 0.45); }\n.gh:hover,\n.goat-lockup:hover { box-shadow: var(--glass-shadow-hover); }\n/* Title over handle, matching the toolbar popup. Laying them side by side\n   fits at 272px on paper but wraps the title the moment the font falls back. */\n.kofi__label { display: flex; flex-direction: column; align-items: flex-start; line-height: 1.25; }\n.kofi__handle { color: rgba(255, 255, 255, 0.82); font-weight: 500; font-size: 11px; }\n\n.cup { width: 22px; height: 22px; overflow: visible; }\n\n/* Steam. Three wisps on staggered delays, drifting as they rise so it reads as\n   convection rather than three identical lines. Paused (not merely invisible)\n   until hover, so it costs nothing while the panel is idle. */\n.steam { opac";
    out += L"ity: 0; transform-origin: 50% 100%; }\n.kofi:hover .steam,\n.kofi:focus-visible .steam { animation: steam 2s var(--ease) infinite; }\n.kofi:hover .steam--b,\n.kofi:focus-visible .steam--b { animation-delay: 0.45s; }\n.kofi:hover .steam--c,\n.kofi:focus-visible .steam--c { animation-delay: 0.9s; }\n\n@keyframes steam {\n  0%   { opacity: 0;    transform: translateY(1px)  translateX(0)     scale(0.6); }\n  22%  { opacity: 0.85; }\n  55%  { opacity: 0.55; transform: translateY(-5px) translateX(1.2px) scale(1); }\n  100% { opacity: 0;    transform: translateY(-10px) translateX(-1px) scale(1.25); }\n}\n\n.kofi:hover .cup__body { animation: cup-tilt 2s var(--ease) infinite; transform-origin: 50% 80%; }\n@keyframes cup-tilt {\n  0%, 100% { transform: rotate(0deg); }\n  50%      { transform: rotate(-3.5deg); }\n}\n\n/* ---- GitHub button ----\n * Ported from uiverse.io/Itskrish01/fuzzy-warthog-48, which is published as\n * Tailwind utility classes; this is the same component rewritten as plain CSS\n * because a shadow root has no Tailwind. The four @keyframes it references are\n * NOT published on that page (they live in the author's own Tailwind config),\n * so they are reconstructed here from how each is used: a gradient blob swept\n * across the border, that blob scaling as it goes, the star turning, and a\n * blurred glow behind the star breathing. Widths match .kofi exactly. */\n\n.gh {\n  all: unset;\n  positio";
    out += L"n: relative;\n  display: block;\n  box-sizing: border-box;\n  width: 100%;\n  margin-top: 8px;\n  padding: 1px;\n  border-radius: 999px;\n  background: #262626;\n  overflow: hidden;\n  cursor: pointer;\n  /* See the note on .kofi: the \"all: unset\" above wipes the transition this\n     rule would otherwise inherit from the .row/.kofi/.gh block. */\n  transition: opacity var(--dur-fast) var(--ease), transform var(--dur-base) var(--ease),\n              box-shadow var(--dur-base) var(--ease);\n}\n.gh:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }\n\n.gh__corner { position: absolute; inset: 0; border-radius: 999px; overflow: hidden; pointer-events: none; }\n.gh__blob {\n  display: block; width: 96px; height: 96px;\n  transform: translate(-50%, -33%); filter: blur(20px);\n  background: linear-gradient(135deg, #7a69f9, #f26378, #f5833f);\n}\n.gh__sweep {\n  position: absolute; inset: 0; pointer-events: none;\n  animation: gh-border-translate 10s ease-in-out infinite alternate;\n}\n.gh__bar {\n  display: block; height: 100%; width: 48px; border-radius: 999px;\n  transform: translateX(-50%); filter: blur(20px);\n  background: linear-gradient(135deg, #7a69f9, #f26378, #f5833f);\n  animation: gh-border-scale 10s ease-in-out infinite alternate;\n}\n.gh__inner {\n  position: relative; z-index: 1;\n  display: flex; align-items: center; justify-content: center; gap: 7px;\n  padding: 8px 16px 8px 12px;";
    out += L"\n  border-radius: 999px;\n  background: rgba(10, 10, 10, 0.9);\n}\n.gh__star { position: relative; display: inline-flex; transition: transform 500ms var(--ease); }\n.gh:hover .gh__star { transform: scale(1.05) rotate(360deg); }\n.gh__star svg { display: block; animation: gh-star-rotate 14s cubic-bezier(0.68, -0.55, 0.27, 1.55) infinite alternate; }\n.gh__glow {\n  position: absolute; top: 50%; left: 50%; width: 44px; height: 44px;\n  border-radius: 999px; transform: translate(-50%, -50%); filter: blur(16px); opacity: 0.3;\n  background: linear-gradient(135deg, #3bc4f2, #7a69f9, #f26378, #f5833f);\n  animation: gh-star-shine 14s ease-in-out infinite alternate;\n}\n.gh__label {\n  font-size: 12px; font-weight: 600; white-space: nowrap;\n  background: linear-gradient(to bottom, #fff, rgba(255, 255, 255, 0.5));\n  -webkit-background-clip: text; background-clip: text; color: transparent;\n  transition: transform var(--dur-fast) var(--ease);\n}\n.gh:hover .gh__label { transform: scale(1.05); }\n\n@keyframes gh-border-translate { from { transform: translateX(0); } to { transform: translateX(100%); } }\n@keyframes gh-border-scale { from { transform: translateX(-50%) scale(1); } to { transform: translateX(-50%) scale(2); } }\n@keyframes gh-star-rotate { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }\n@keyframes gh-star-shine {\n  from { opacity: 0.14; transform: translate(-50%, -50%) sca";
    out += L"le(0.8); }\n  to   { opacity: 0.45; transform: translate(-50%, -50%) scale(1.2); }\n}\n\n.gh { margin-bottom: 0; }\n\n/* ---- Goat lockup banner ----\n * Hover component from brand/lockup-hover, not the looping SVG. The two\n * campaign lines sit above the lockup. Animation is :hover on .goat-lockup\n * only -- hovering the sentences or StarGithub must not play it. */\n\n.goat {\n  display: block;\n  box-sizing: border-box;\n  width: 100%;\n  margin-top: 16px;\n  margin-bottom: 2px;\n  color: var(--ink-cream);\n}\n.goat__copy { display: flex; flex-direction: column; gap: 4px; margin: 0 0 8px; }\n.goat__line { margin: 0; font-size: 10.5px; line-height: 1.4; font-weight: 500; }\n.goat__line--ask { color: var(--ink-muted); font-weight: 400; }\n.goat .goat-lockup {\n  font-size: 10px;\n  --gl-seal-scale: 1.36;\n  --gl-name-min: 13px;\n  --gl-tag-min: 7px;\n  display: flex;\n  flex-wrap: nowrap;\n  align-items: center;\n  width: 100%;\n  max-width: 100%;\n  gap: 0.65em;\n  box-sizing: border-box;\n  padding: 10px 10px;\n  border-radius: 8px;\n  overflow: hidden;\n  background: #0b0b0d;\n  cursor: pointer;\n  text-decoration: none;\n  color: inherit;\n  transition: transform var(--dur-base) var(--ease), box-shadow var(--dur-base) var(--ease);\n}\n.goat .goat-lockup:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }\n.goat .goat-lockup__word {\n  flex: 1 1 auto;\n  min-width: 0;\n  display: flex;\n  flex-direc";
    out += L"tion: column;\n  align-items: flex-start;\n  justify-content: center;\n  gap: 0.4em;\n}\n.goat .goat-lockup__name,\n.goat .goat-lockup__tag {\n  display: block;\n  width: max-content;\n  max-width: 100%;\n  margin: 0;\n  padding: 0;\n  text-align: left;\n  text-indent: 0;\n  white-space: nowrap;\n}\n.goat .goat-lockup__name { letter-spacing: 0.18em; }\n.goat .goat-lockup__tag { letter-spacing: 0.12em; }\n.goat .goat-lockup.goat-lockup--paper {\n  background: #f6efe6;\n}\n\n/* ---- health notice, only rendered when something is actually wrong ---- */\n.warn {\n  display: none;\n  margin: 8px 0 0;\n  padding: 7px 9px;\n  border-radius: 9px;\n  font-size: 10.5px;\n  line-height: 1.45;\n  background: rgba(229, 72, 77, 0.14);\n  border: 0.5px solid rgba(229, 72, 77, 0.4);\n  color: #f3b9bb;\n}\n.shell.has-warning .warn { display: block; }\n\n@media (prefers-reduced-motion: reduce) {\n  .shell, .shell:hover, .body, .row, .pill, .kofi, .gh, .goat, .goat-lockup, .moon, .chev, .thumb, .track {\n    transition: none !important;\n    transform: none !important;\n  }\n  .kofi:hover .steam, .kofi:focus-visible .steam, .kofi:hover .cup__body { animation: none !important; }\n  .gh__sweep, .gh__bar, .gh__star svg, .gh__glow { animation: none !important; }\n  .gh:hover .gh__star, .gh:hover .gh__label { transform: none !important; }\n  /* Without the rise animation the rows still need to be visible when open. */\n  .shell.is-open .row, .sh";
    out += L"ell.is-open .kofi, .shell.is-open .gh, .shell.is-open .goat { opacity: 1; }\n}\n\n/* ==========================================================================\n   GOATPROJECT - animated lockup\n\n   Hover or focus: the stamp warms and blooms - it never moves or changes size.\n   Inside it the seal glyph cross-fades to a solid thumbs-up, and a spark fires\n   above the tip. Meteors run behind the mark continuously; hovering only fades\n   them in. Leaving reverses everything, faster than it arrived.\n\n   No dependencies. No JavaScript required. Scale it with font-size.\n   ========================================================================== */\n\n.goat-lockup {\n  /* ---- scale knob: everything derives from font-size ---- */\n  font-size: 20px;\n\n  /* ---- palette ---- */\n  --gl-cream: #ece7db;\n  --gl-glyph: #f6efe6;\n  --gl-seal: #b3382c;\n  --gl-seal-lit: #c8412f;\n  --gl-name: #f2f3f5;\n  --gl-tag: #9b9da4;\n  --gl-spark: #f7ead6;\n  --gl-focus: rgba(246, 239, 230, 0.72);\n  --gl-meteor-tail: rgba(236, 231, 219, 0);\n  --gl-meteor-head: rgba(236, 231, 219, 0.68);\n  --gl-meteor-halo: rgba(236, 231, 219, 0.55);\n\n  /* ---- motion ---- */\n  --gl-in: cubic-bezier(0.16, 1, 0.3, 1);\n  --gl-out: cubic-bezier(0.4, 0, 0.2, 1);\n  --gl-t-out: 360ms;          /* leaving is always faster than arriving */\n  --gl-t-fade: 450ms;         /* the length of the glyph cross-fade */\n\n  /* ---- type floors: below th";
    out += L"ese the wordmark stops scaling with the mark ---- */\n  --gl-name-min: 20px;\n  --gl-tag-min: 10px;\n\n  /* ---- stamp: 1 keeps the brand lockup's own proportion. Raise it on small\n          lockups, where 36 of 250 viewBox units renders under ~12px and the\n          thumbs-up inside stops reading. Static - it never changes on hover. ---- */\n  --gl-seal-scale: 1;\n\n  position: relative;\n  display: inline-flex;\n  align-items: center;\n  gap: 2em;\n  isolation: isolate;\n  overflow: hidden;            /* fallback for browsers without `clip` */\n  overflow: clip;              /* the meteor layer is inset past the lockup on\n                                  every side; without this it can push page-level\n                                  horizontal scroll when the lockup sits near the\n                                  viewport edge. `clip` does not create a scroll\n                                  container and does not clip the focus ring. */\n  color: var(--gl-name);\n  text-decoration: none;\n  -webkit-tap-highlight-color: transparent;\n}\n\n.goat-lockup--paper {\n  --gl-cream: #1a1917;\n  --gl-glyph: #f6efe6;\n  --gl-name: #1a1917;\n  --gl-tag: #4f4a42;\n  --gl-spark: #b3382c;\n  --gl-focus: rgba(26, 25, 23, 0.72);\n  --gl-meteor-tail: rgba(26, 25, 23, 0);\n  --gl-meteor-head: rgba(26, 25, 23, 0.42);\n  --gl-meteor-halo: rgba(179, 56, 44, 0.4);\n}\n\n.goat-lockup:focus-visible {\n  outline: 1px solid var(";
    out += L"--gl-focus);\n  outline-offset: 0.6em;\n  border-radius: 2px;\n}\n\n.goat-lockup ::selection { background: var(--gl-seal); color: #f6efe6; }\n\n/* --------------------------------------------------------------------------\n   Mark\n   -------------------------------------------------------------------------- */\n\n.goat-lockup__mark {\n  position: relative;\n  z-index: 1;\n  display: block;\n  height: 5.4em;\n  flex: none;\n}\n\n.goat-lockup__svg {\n  display: block;\n  height: 100%;\n  width: auto;\n  overflow: visible;\n}\n\n.gl-head > * { fill: var(--gl-cream); }\n\n/* --------------------------------------------------------------------------\n   Seal - fixed size. Hover lights it: the face warms and a soft bloom appears\n   behind it. Nothing in here moves or scales.\n   -------------------------------------------------------------------------- */\n\n.gl-seal {\n  transform-box: fill-box;      /* bbox is exactly the 36x36 stamp square */\n  transform-origin: 50% 50%;\n  transform: scale(var(--gl-seal-scale, 1));\n}\n\n.gl-seal-face { fill: var(--gl-seal); transition: fill var(--gl-t-out) var(--gl-out); }\n\n.gl-seal-glow {\n  fill: var(--gl-seal);\n  opacity: 0;\n  filter: blur(5px);\n  transition: opacity var(--gl-t-out) var(--gl-out);\n}\n\n.gl-glyph { overflow: visible; }\n\n/* --------------------------------------------------------------------------\n   The glyph cross-fade: character out, thumbs-up in.\n   The characte";
    out += L"r is the real \u7F8A outline taken from SimSun - the font the brand\n   lockup's own stack (goat-mark-cream.svg) resolves to - baked to a path so it\n   needs no CJK font installed and renders identically inside an <img>.\n   The thumb is a solid silhouette with no internal detail, which is what keeps\n   it readable at stamp size - roughly 20px wide on a hero lockup.\n   -------------------------------------------------------------------------- */\n\n.gl-char {\n  fill: var(--gl-glyph);\n  opacity: 1;\n  transition: opacity var(--gl-t-out) var(--gl-out);\n}\n\n.gl-thumb {\n  fill: var(--gl-glyph);\n  opacity: 0;\n  transition: opacity var(--gl-t-out) var(--gl-out);\n}\n\n/* --------------------------------------------------------------------------\n   Spark above the thumb tip\n   -------------------------------------------------------------------------- */\n\n.gl-burst { opacity: 0; }\n\n.gl-ray {\n  stroke: var(--gl-spark);\n  stroke-width: 3.2;\n  stroke-linecap: round;\n  stroke-dasharray: 9 32;\n  stroke-dashoffset: 9;\n  opacity: 0;\n}\n\n.gl-ring {\n  fill: none;\n  stroke: var(--gl-spark);\n  stroke-width: 3;\n  opacity: 0;\n  transform-box: fill-box;\n  transform-origin: 50% 50%;\n}\n\n.gl-ember {\n  fill: var(--gl-spark);\n  opacity: 0;\n  transform-box: fill-box;\n  transform-origin: 50% 50%;\n}\n\n/* --------------------------------------------------------------------------\n   Wordmark\n   ------------------------------";
    out += L"-------------------------------------------- */\n\n.goat-lockup__word {\n  position: relative;\n  z-index: 1;\n  display: flex;\n  flex-direction: column;\n  gap: 0.62em;\n  font-family: \"Inter\", \"Helvetica Neue\", \"Segoe UI\", Arial, sans-serif;\n  font-weight: 300;\n}\n\n.goat-lockup__name {\n  font-size: max(var(--gl-name-min), 1em);\n  line-height: 1;\n  letter-spacing: 0.24em;\n  text-transform: uppercase;\n  text-indent: 0.24em;         /* recentre against the trailing tracking */\n  color: var(--gl-name);\n  white-space: nowrap;\n}\n\n.goat-lockup__tag {\n  font-size: max(var(--gl-tag-min), 0.43em);\n  font-weight: 500;\n  line-height: 1;\n  letter-spacing: 0.28em;\n  text-transform: uppercase;\n  text-indent: 0.28em;\n  color: var(--gl-tag);\n  white-space: nowrap;\n  transition: color var(--gl-t-out) var(--gl-out);\n}\n\n/* --------------------------------------------------------------------------\n   Meteors - always in motion. Hover only fades the layer in, so the streaks\n   are already mid-flight when they appear rather than starting from a standstill.\n   -------------------------------------------------------------------------- */\n\n.goat-lockup__meteors {\n  position: absolute;\n  inset: -22% -12%;\n  z-index: 0;\n  overflow: hidden;\n  pointer-events: none;\n  opacity: 0;\n  transition: opacity var(--gl-t-out) var(--gl-out);\n  -webkit-mask-image: radial-gradient(120% 100% at 62% 40%, #000 34%, transparent 7";
    out += L"8%);\n  mask-image: radial-gradient(120% 100% at 62% 40%, #000 34%, transparent 78%);\n}\n\n.goat-lockup__meteors i {\n  position: absolute;\n  top: 0;\n  left: 0;\n  width: 1px;\n  height: var(--gl-m-h, 4.4em);\n  border-radius: 1px;\n  background: linear-gradient(to bottom, var(--gl-meteor-tail), var(--gl-meteor-head));\n  rotate: 34deg;               /* long axis aligned to the fall direction */\n  translate: 3.2em -4.8em;\n  animation: gl-meteor var(--gl-m-d, 3.3s) linear var(--gl-m-delay, 0s) infinite;\n}\n\n.goat-lockup__meteors i::after {\n  content: \"\";\n  position: absolute;\n  left: 50%;\n  bottom: 0;\n  width: 2.5px;\n  height: 2.5px;\n  border-radius: 50%;\n  background: var(--gl-cream);\n  box-shadow: 0 0 7px 1px var(--gl-meteor-halo);\n  translate: -50% 40%;\n}\n\n.goat-lockup__meteors i:nth-child(1) { left: 74%; top: 6%;  --gl-m-h: 5.2em; --gl-m-d: 2.85s; --gl-m-delay: 0s; }\n.goat-lockup__meteors i:nth-child(2) { left: 52%; top: -4%; --gl-m-h: 3.4em; --gl-m-d: 3.9s;  --gl-m-delay: -.48s; }\n.goat-lockup__meteors i:nth-child(3) { left: 89%; top: 22%; --gl-m-h: 4.6em; --gl-m-d: 3.15s; --gl-m-delay: -1.11s; }\n.goat-lockup__meteors i:nth-child(4) { left: 33%; top: 12%; --gl-m-h: 2.8em; --gl-m-d: 4.65s; --gl-m-delay: -1.65s; }\n.goat-lockup__meteors i:nth-child(5) { left: 64%; top: 38%; --gl-m-h: 3.9em; --gl-m-d: 3.6s;  --gl-m-delay: -.27s; }\n.goat-lockup__meteors i:nth-child(6) { left: 18%; top: -8";
    out += L"%; --gl-m-h: 4.1em; --gl-m-d: 4.2s;  --gl-m-delay: -1.43s; }\n.goat-lockup__meteors i:nth-child(7) { left: 97%; top: -2%; --gl-m-h: 3.1em; --gl-m-d: 3.45s; --gl-m-delay: -2.18s; }\n.goat-lockup__meteors i:nth-child(8) { left: 44%; top: 30%; --gl-m-h: 5.6em; --gl-m-d: 2.55s; --gl-m-delay: -.87s; }\n.goat-lockup__meteors i:nth-child(9) { left: 82%; top: 48%; --gl-m-h: 2.6em; --gl-m-d: 5.1s;  --gl-m-delay: -2.7s; }\n\n@keyframes gl-meteor {\n  0%   { translate: 3.2em -4.8em; opacity: 0; }\n  9%   { opacity: 1; }\n  68%  { opacity: 1; }\n  100% { translate: -3.4em 5.1em; opacity: 0; }\n}\n\n/* ==========================================================================\n   ACTIVE STATE\n   ========================================================================== */\n\n.goat-lockup:hover .goat-lockup__meteors,\n.goat-lockup:focus-visible .goat-lockup__meteors,\n.goat-lockup.is-active .goat-lockup__meteors {\n  opacity: 1;\n  transition-duration: 630ms;\n}\n\n.goat-lockup:hover .goat-lockup__tag,\n.goat-lockup:focus-visible .goat-lockup__tag,\n.goat-lockup.is-active .goat-lockup__tag {\n  color: var(--gl-name);\n  transition-duration: 630ms;\n}\n\n.goat-lockup:hover .gl-seal-face,\n.goat-lockup:focus-visible .gl-seal-face,\n.goat-lockup.is-active .gl-seal-face {\n  fill: var(--gl-seal-lit);\n  transition-duration: 690ms;\n}\n\n.goat-lockup:hover .gl-seal-glow,\n.goat-lockup:focus-visible .gl-seal-glow,\n.goat-lockup.is-act";
    out += L"ive .gl-seal-glow {\n  opacity: 0.7;\n  transition: opacity 690ms var(--gl-in);\n}\n\n/* ---- the cross-fade ---- */\n\n.goat-lockup:hover .gl-char,\n.goat-lockup:focus-visible .gl-char,\n.goat-lockup.is-active .gl-char {\n  opacity: 0;\n  transition: opacity var(--gl-t-fade) linear;\n}\n\n.goat-lockup:hover .gl-thumb,\n.goat-lockup:focus-visible .gl-thumb,\n.goat-lockup.is-active .gl-thumb {\n  opacity: 1;\n  transition: opacity var(--gl-t-fade) linear 180ms;\n}\n\n/* ---- the spark ---- */\n\n.goat-lockup:hover .gl-burst,\n.goat-lockup:focus-visible .gl-burst,\n.goat-lockup.is-active .gl-burst { opacity: 1; }\n\n.goat-lockup:hover .gl-ray,\n.goat-lockup:focus-visible .gl-ray,\n.goat-lockup.is-active .gl-ray {\n  animation: gl-ray 690ms var(--gl-in) var(--gl-ray-lag, 0ms) both;\n}\n\n.gl-ray--1 { --gl-ray-lag: 720ms; }\n.gl-ray--2 { --gl-ray-lag: 765ms; }\n.gl-ray--3 { --gl-ray-lag: 738ms; }\n.gl-ray--4 { --gl-ray-lag: 792ms; }\n.gl-ray--5 { --gl-ray-lag: 752ms; }\n.gl-ray--6 { --gl-ray-lag: 816ms; }\n\n.goat-lockup:hover .gl-ring,\n.goat-lockup:focus-visible .gl-ring,\n.goat-lockup.is-active .gl-ring {\n  animation: gl-ring 930ms var(--gl-in) 705ms both;\n}\n\n.goat-lockup:hover .gl-ember,\n.goat-lockup:focus-visible .gl-ember,\n.goat-lockup.is-active .gl-ember {\n  animation: gl-ember 1350ms var(--gl-in) var(--gl-ember-lag, 840ms) both;\n}\n\n.gl-ember--a { --gl-ember-lag: 840ms; --gl-ex: -13px; --gl-ey: -28px; }\n.gl-ember--b";
    out += L" { --gl-ember-lag: 975ms; --gl-ex: 15px;  --gl-ey: -21px; }\n.gl-ember--c { --gl-ember-lag: 908ms; --gl-ex: 3px;   --gl-ey: -34px; }\n\n@keyframes gl-ray {\n  0%   { stroke-dashoffset: 9; opacity: 0; }\n  22%  { opacity: 1; }\n  100% { stroke-dashoffset: -32; opacity: 0; }\n}\n\n@keyframes gl-ring {\n  0%   { transform: scale(0.3); opacity: 0; }\n  18%  { opacity: 0.85; }\n  100% { transform: scale(1.9); opacity: 0; }\n}\n\n@keyframes gl-ember {\n  0%   { transform: translate(0, 0) scale(0.4); opacity: 0; }\n  25%  { opacity: 0.9; }\n  100% { transform: translate(var(--gl-ex, 6px), var(--gl-ey, -16px)) scale(1); opacity: 0; }\n}\n\n/* ==========================================================================\n   REDUCED MOTION - the cross-fade survives, the travelling parts do not\n   ========================================================================== */\n\n@media (prefers-reduced-motion: reduce) {\n  .goat-lockup__meteors i {\n    animation: none;\n    translate: 0 0;\n    opacity: 0.5;\n  }\n\n  .goat-lockup:hover .gl-ray,\n  .goat-lockup:focus-visible .gl-ray,\n  .goat-lockup.is-active .gl-ray,\n  .goat-lockup:hover .gl-ember,\n  .goat-lockup:focus-visible .gl-ember,\n  .goat-lockup.is-active .gl-ember { animation: none; opacity: 0; }\n\n  .goat-lockup:hover .gl-ring,\n  .goat-lockup:focus-visible .gl-ring,\n  .goat-lockup.is-active .gl-ring {\n    animation: none;\n    opacity: 0.5;\n    transform: scale(1.15)";
    out += L";\n    transition: opacity 330ms linear 300ms;\n  }\n}\n\n\n.go-row{display:flex;flex-direction:row;align-items:stretch;gap:10px}\n.go-row>*{flex:0 0 auto}\n.go-row>.kofi{width:max-content;margin-top:0}\n.go-row>.gh{width:max-content;margin-top:0;display:flex;align-items:stretch}\n.go-row>.gh>.gh__inner{flex:1 1 auto}\n.go-item{display:flex;align-items:center;box-sizing:border-box;min-width:0;margin:0}\n.go-item--copy{width:236px}\n.go-item--lock{width:190px;align-items:stretch}\n.go-row>.go-item--lock .goat-lockup{font-size:5.069px}\n.go-row>.go-item .goat__copy{margin:0;gap:3px;flex:1 1 auto;min-width:0}\n.shell.is-open{width:831px}\n</style><div class='shell is-open'><div class='body__pad'><div class=\"go-row\"><button type=\"button\" class=\"kofi\"><svg class=\"cup\" viewBox=\"0 0 24 24\" fill=\"none\" aria-hidden=\"true\"><g class=\"steam steam--a\"><path d=\"M9 6.4c0-1 .9-1.2.9-2.2S9 2.6 9 2.6\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" opacity=\"0.9\"/></g><g class=\"steam steam--b\"><path d=\"M12 6.4c0-1 .9-1.2.9-2.2S12 2.6 12 2.6\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" opacity=\"0.9\"/></g><g class=\"steam steam--c\"><path d=\"M15 6.4c0-1 .9-1.2.9-2.2S15 2.6 15 2.6\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" opacity=\"0.9\"/></g><g class=\"cup__body\"><path d=\"M4 9h12v5a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5V9Z\" fill=\"currentColor\"/><path d=\"M16 10.5h1.6a2.4 ";
    out += L"2.4 0 0 1 0 4.8H16\" stroke=\"currentColor\" stroke-width=\"1.7\" fill=\"none\"/><path d=\"M3 21h14\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\"/></g></svg><span class=\"kofi__label\"><span>Support me on Ko-fi</span><span class=\"kofi__handle\">@IRP_HongKong</span></span></button><button type=\"button\" class=\"gh\"><span class=\"gh__corner\"><span class=\"gh__blob\"></span></span><span class=\"gh__sweep\"><span class=\"gh__bar\"></span></span><span class=\"gh__inner\"><span class=\"gh__star\"><svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" aria-hidden=\"true\"><path d=\"M11.5268 2.29489C11.5706 2.20635 11.6383 2.13183 11.7223 2.07972C11.8062 2.02761 11.903 2 12.0018 2C12.1006 2 12.1974 2.02761 12.2813 2.07972C12.3653 2.13183 12.433 2.20635 12.4768 2.29489L14.7868 6.97389C14.939 7.28186 15.1636 7.5483 15.4414 7.75035C15.7192 7.95239 16.0419 8.08401 16.3818 8.13389L21.5478 8.88989C21.6457 8.90408 21.7376 8.94537 21.8133 9.00909C21.8889 9.07282 21.9452 9.15644 21.9758 9.2505C22.0064 9.34456 22.0101 9.4453 21.9864 9.54133C21.9627 9.63736 21.9126 9.72485 21.8418 9.79389L18.1058 13.4319C17.8594 13.672 17.6751 13.9684 17.5686 14.2955C17.4622 14.6227 17.4369 14.9708 17.4948 15.3099L18.3768 20.4499C18.3941 20.5477 18.3835 20.6485 18.3463 20.7406C18.3091 20.8327 18.2467 20.9125 18.1663 20.9709C18.086 21.0293 17.9908 21.0639 17.8917 21.0708C17.7926 21.0777 17.6935 21.0566 17.6058 21.009";
    out += L"9L12.9878 18.5819C12.6835 18.4221 12.345 18.3386 12.0013 18.3386C11.6576 18.3386 11.3191 18.4221 11.0148 18.5819L6.3978 21.0099C6.31013 21.0563 6.2112 21.0772 6.11225 21.0701C6.0133 21.0631 5.91832 21.0285 5.83809 20.9701C5.75787 20.9118 5.69563 20.8321 5.65846 20.7401C5.62128 20.6482 5.61066 20.5476 5.6278 20.4499L6.5088 15.3109C6.567 14.9716 6.54178 14.6233 6.43534 14.2959C6.32889 13.9686 6.14441 13.672 5.8978 13.4319L2.1618 9.79489C2.09039 9.72593 2.03979 9.63829 2.01576 9.54197C1.99173 9.44565 1.99524 9.34451 2.02588 9.25008C2.05652 9.15566 2.11307 9.07174 2.18908 9.00788C2.26509 8.94402 2.3575 8.90279 2.4558 8.88889L7.6208 8.13389C7.96106 8.08439 8.28419 7.95295 8.56238 7.75088C8.84058 7.54881 9.0655 7.28216 9.2178 6.97389L11.5268 2.29489Z\" fill=\"url(#gmdmStarFill)\" stroke=\"url(#gmdmStarStroke)\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><defs><linearGradient id=\"gmdmStarFill\" x1=\"-0.5\" y1=\"9\" x2=\"15.5\" y2=\"-1.5\" gradientUnits=\"userSpaceOnUse\"><stop stop-color=\"#7A69F9\"/><stop offset=\"0.575\" stop-color=\"#F26378\"/><stop offset=\"1\" stop-color=\"#F5833F\"/></linearGradient><linearGradient id=\"gmdmStarStroke\" x1=\"-0.5\" y1=\"9\" x2=\"15.5\" y2=\"-1.5\" gradientUnits=\"userSpaceOnUse\"><stop stop-color=\"#7A69F9\"/><stop offset=\"0.575\" stop-color=\"#F26378\"/><stop offset=\"1\" stop-color=\"#F5833F\"/></linearGradient></defs></svg><span class=\"gh__glow\"></span></span><span class=\"gh__label\">";
    out += L"Star Project on Github</span></span></button><div class=\"go-item go-item--copy\"><div class=\"goat__copy\"><span class=\"goat__line\">Goat Project - Help fight Cancer, Alzheimer&rsquo;s, Parkinson&rsquo;s, COVID-19, Dengue, Hepatitis C etc.</span><span class=\"goat__line goat__line--ask\">Contribute your idle compute to Earn GOAT.</span></div></div><div class=\"goat go-item go-item--lock\"><a class=\"goat-lockup\" href=\"https://dagoat.io\" target=\"_blank\" rel=\"noopener noreferrer\" data-goat-mark><span class=\"goat-lockup__meteors\" aria-hidden=\"true\"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></span><span class=\"goat-lockup__mark\" aria-hidden=\"true\"><svg class=\"goat-lockup__svg\" viewBox=\"46 -16 220 250\" xmlns=\"http://www.w3.org/2000/svg\" focusable=\"false\"><g class=\"gl-head\"><path d=\"M62 210 C74 148 120 98 190 80 C152 106 106 150 82 216 Z\"/><path d=\"M186 84 C214 62 226 32 210 8 C216 36 200 62 174 80 Z\"/><path d=\"M170 82 C190 60 194 34 180 16 C186 40 172 62 156 78 Z\"/><path d=\"M188 82 C206 90 218 104 222 122 C212 106 200 94 182 90 Z\"/><path d=\"M206 122 C215 134 217 149 209 160 C212 147 208 133 200 127 Z\"/><circle cx=\"197\" cy=\"99\" r=\"3.6\"/></g><g class=\"gl-seal\"><rect class=\"gl-seal-glow\" x=\"214\" y=\"182\" width=\"36\" height=\"36\" rx=\"4\"/><rect class=\"gl-seal-face\" x=\"214\" y=\"182\" width=\"36\" height=\"36\" rx=\"4\"/><svg class=\"gl-glyph\" x=\"214\" y=\"182\" width=\"36\" height=\"36\" viewBox";
    out += L"=\"0 0 100 100\"><path class=\"gl-thumb\" d=\"M30 50 C26 50 24 52 24 56 L24 87 C24 91 26 93 30 93 L73 93 C79 93 84 90 85 84 L89 55 C90 49 86 44 80 44 L63 44 C65 38 67 25 65 18 C63 12 55 12 53 18 C51 24 53 33 51 42 C50 47 47 50 42 50 Z\" transform=\"translate(-5 -3)\"/><path class=\"gl-char\" d=\"M33.5 18.12Q39.14 21.51 41.54 23.62Q43.93 25.74 43.65 27.85Q43.37 29.97 42.24 30.96Q41.11 31.94 40.55 31.94Q39.42 31.94 38.57 29.12Q37.45 25.17 32.93 18.97ZM20.52 33.07H52.68Q58.89 23.76 60.86 16.99L66.79 20.66Q63.96 22.07 61.14 25.74Q58.04 29.41 54.37 33.07H68.2L72.43 28.84L77.79 34.77H51.55V47.46H63.96L68.2 43.79L72.99 49.15H51.55V62.13H71.58L76.1 57.9L81.46 63.82H51.55V73.7Q51.55 76.8 51.83 81.32L47.04 83.01Q47.32 78.78 47.32 63.82H27.85Q24.19 63.82 21.08 64.67L18.54 62.13H47.32V49.15H35.47Q31.8 49.15 28.7 50L26.16 47.46H47.32V34.77H29.83Q26.16 34.77 23.06 35.61Z\"/><g class=\"gl-burst\" transform=\"translate(53 0)\" fill=\"none\"><circle class=\"gl-ring\" cx=\"0\" cy=\"0\" r=\"12\"/><line class=\"gl-ray gl-ray--1\" transform=\"rotate(-168)\" x1=\"10\" y1=\"0\" x2=\"40\" y2=\"0\"/><line class=\"gl-ray gl-ray--2\" transform=\"rotate(-138)\" x1=\"10\" y1=\"0\" x2=\"40\" y2=\"0\"/><line class=\"gl-ray gl-ray--3\" transform=\"rotate(-108)\" x1=\"10\" y1=\"0\" x2=\"40\" y2=\"0\"/><line class=\"gl-ray gl-ray--4\" transform=\"rotate(-76)\" x1=\"10\" y1=\"0\" x2=\"40\" y2=\"0\"/><line class=\"gl-ray gl-ray--5\" transform=\"rotate(-44)\" x1=\"10\" y1=\"0\" x2=\"40\" y2=\"0\"/>";
    out += L"<line class=\"gl-ray gl-ray--6\" transform=\"rotate(-14)\" x1=\"10\" y1=\"0\" x2=\"40\" y2=\"0\"/><circle class=\"gl-ember gl-ember--a\" cx=\"-7\" cy=\"-2\" r=\"2.2\"/><circle class=\"gl-ember gl-ember--b\" cx=\"8\" cy=\"-5\" r=\"1.9\"/><circle class=\"gl-ember gl-ember--c\" cx=\"0\" cy=\"-9\" r=\"1.6\"/></g></svg></g></svg></span><span class=\"goat-lockup__word\"><span class=\"goat-lockup__name\">Goatproject</span><span class=\"goat-lockup__tag\">The People&rsquo;s Compute Commons</span></span></a></div></div></div></div></script><script>var host=document.getElementById('h');var r=host.attachShadow({mode:'open'});r.innerHTML=document.getElementById('p').textContent;var U={kofi:'https://ko-fi.com/irp_hongkong',gh:'https://github.com/charlie754/Game-Optimizer-CPUs-Threads-Optimizer'};r.addEventListener('click',function(e){var t=e.target;if(!t||!t.closest)return;var b=t.closest('.kofi,.gh');if(!b)return;e.preventDefault();location.href=b.classList.contains('kofi')?U.kofi:U.gh;});</script>";
}

}  // namespace cd
